name: Struct_By_value
version: 0.0.1
description: >-
    Bindings to struct
author: Dhanush
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
  libclang: ^0.0.1+1
dev_dependencies:
  test: ^1.5.3
